# DEEP LEARNING
# Pytorch Basic

In [21]:
import torch

In [22]:
torch.cuda.is_available()

False

Dataset with pytorch

In [23]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [24]:
df = pd.read_csv('./Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [25]:
df.shape

(150, 6)

In [26]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

# Chia dữ liệu bởi test size = 20%

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

In [27]:
len(y_train)

120

In [28]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [29]:
# Tính đạo hàm bằng pytorch

# Cho y = 2x^4 + x^3 + 3x^2 + 5*x + 1

# Tính y'

In [30]:
import torch

In [31]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [32]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)


tensor(63., grad_fn=<AddBackward0>)


In [33]:
y.grad_fn

In [34]:
# Thực hiện lan truyền ngược và tính toán các gradient

y.backward()

In [35]:
# 8x^3 + 3x^2 + 6x + 5

x.grad

tensor(93.)

# BTVN 01

Cho y = 5x^5 + 6x^3 - 3x + 1

Cho biết độ dốc của đa thức trên ở điểm nào

In [7]:
import torch

# Tạo tensor x với requires_grad=True
# Thử với nhiều điểm khác nhau
diem_can_kiem_tra = [0.0, 1.0, 2.0, -1.0, 0.5]

print("Hàm số: y = 5x^5 + 6x^3 - 3x + 1")
print("Đạo hàm: dy/dx = 25x^4 + 18x^2 - 3")
print("\nĐộ dốc của đa thức tại các điểm:\n")

for diem in diem_can_kiem_tra:
    x = torch.tensor(diem, requires_grad=True)
    
    # Định nghĩa hàm số
    y = 5*x**5 + 6*x**3 - 3*x + 1
    
    # Tính gradient
    y.backward()
    
    print(f"Tại x = {x.item():6.1f}: y = {y.item():10.4f}, độ dốc dy/dx = {x.grad.item():10.4f}")

print("\n=> Độ dốc thay đổi tùy theo vị trí x")
print("=> Độ dốc = 0 khi x ≈ -0.61 hoặc x = 0 (điểm cực trị)")

Hàm số: y = 5x^5 + 6x^3 - 3x + 1
Đạo hàm: dy/dx = 25x^4 + 18x^2 - 3

Độ dốc của đa thức tại các điểm:

Tại x =    0.0: y =     1.0000, độ dốc dy/dx =    -3.0000
Tại x =    1.0: y =     9.0000, độ dốc dy/dx =    40.0000
Tại x =    2.0: y =   203.0000, độ dốc dy/dx =   469.0000
Tại x =   -1.0: y =    -7.0000, độ dốc dy/dx =    40.0000
Tại x =    0.5: y =     0.4062, độ dốc dy/dx =     3.0625

=> Độ dốc thay đổi tùy theo vị trí x
=> Độ dốc = 0 khi x ≈ -0.61 hoặc x = 0 (điểm cực trị)


# BTVN 02

Tạo 1 tensor ban đầu có giá trị là 2

Định nghĩa hàm số  và tính gradient

y = x^3 + 2x^2 + 5x + 1

Hãy tính đạo hàm dy/dx tại giá trị của x

Dùng phương pháp Gradient Descent với Learning Rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

In [6]:
import torch

# Tạo tensor ban đầu với giá trị 2
x = torch.tensor(2.0, requires_grad=True)

# Learning rate
alpha = 0.1

# Số vòng lặp
epochs = 10

print("Hàm số: y = x^3 + 2x^2 + 5x + 1")
print(f"Learning Rate: {alpha}")
print(f"Giá trị x ban đầu: {x.item()}\n")

for i in range(epochs):
    # Định nghĩa hàm số
    y = x**3 + 2*x**2 + 5*x + 1
    
    # Tính gradient
    y.backward()
   
    print(f"Vòng {i+1}: x = {x.item():.4f}, y = {y.item():.4f}, dy/dx = {x.grad.item():.4f}")
    
    # Cập nhật x bằng Gradient Descent: x = x - alpha * gradient
    with torch.no_grad():
        x -= alpha * x.grad
    
    # Reset gradient về 0 cho vòng lặp tiếp theo
    x.grad.zero_()

print(f"\nGiá trị x cuối cùng: {x.item():.4f}")

Hàm số: y = x^3 + 2x^2 + 5x + 1
Learning Rate: 0.1
Giá trị x ban đầu: 2.0

Vòng 1: x = 2.0000, y = 27.0000, dy/dx = 25.0000
Vòng 2: x = -0.5000, y = -1.1250, dy/dx = 3.7500
Vòng 3: x = -0.8750, y = -2.5137, dy/dx = 3.7969
Vòng 4: x = -1.2547, y = -4.1001, dy/dx = 4.7040
Vòng 5: x = -1.7251, y = -6.8073, dy/dx = 7.0274
Vòng 6: x = -2.4278, y = -13.6609, dy/dx = 12.9717
Vòng 7: x = -3.7250, y = -41.5604, dy/dx = 31.7268
Vòng 8: x = -6.8977, y = -266.5102, dy/dx = 120.1433
Vòng 9: x = -18.9120, y = -6142.3750, dy/dx = 1002.3439
Vòng 10: x = -119.1464, y = -1663589.5000, dy/dx = 42116.0117

Giá trị x cuối cùng: -4330.7476


# BTVN 03

Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1-10) và y là số điểm được tính theo công thức y = 3x + 5 + noise 

Với noise là một giá trị ngẫu nhiên nhỏ

1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với Learning Rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình.

In [8]:
import torch
import numpy as np

# Tạo tập dữ liệu giả lập
np.random.seed(42)
n_samples = 100

# x: số giờ học (ngẫu nhiên từ 1-10)
x_data = np.random.uniform(1, 10, n_samples)

# y = 3x + 5 + noise
noise = np.random.normal(0, 0.5, n_samples)
y_data = 3 * x_data + 5 + noise

# Chuyển sang tensor
x = torch.FloatTensor(x_data).reshape(-1, 1)
y = torch.FloatTensor(y_data).reshape(-1, 1)

# 1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Công thức thực: y = 3x + 5 + noise")
print(f"Tham số khởi tạo: w = {w.item():.4f}, b = {b.item():.4f}\n")

# Learning rate và số epochs
alpha = 0.01
epochs = 100

for epoch in range(epochs):
    # Dự đoán: y_pred = w*x + b
    y_pred = w * x + b
    
    # 2. Tính MSE (Mean Squared Error)
    loss = ((y_pred - y) ** 2).mean()
    
    # 3. Tính Gradient
    loss.backward()
    
    # 4. Cập nhật tham số w và b bằng Gradient Descent
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
        
        # Reset gradient
        w.grad.zero_()
        b.grad.zero_()
    
    # In thông tin mỗi 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")

print(f"\n5. Kết quả cuối cùng:")
print(f"w = {w.item():.4f} (mong đợi: 3.0)")
print(f"b = {b.item():.4f} (mong đợi: 5.0)")
print(f"Loss cuối cùng: {loss.item():.4f}")

Công thức thực: y = 3x + 5 + noise
Tham số khởi tạo: w = 0.5903, b = -0.4278

Epoch  10: Loss = 5.1409, w = 3.7192, b = 0.2553
Epoch  20: Loss = 4.7582, w = 3.6898, b = 0.4481
Epoch  30: Loss = 4.4051, w = 3.6615, b = 0.6333
Epoch  40: Loss = 4.0794, w = 3.6343, b = 0.8112
Epoch  50: Loss = 3.7789, w = 3.6082, b = 0.9820
Epoch  60: Loss = 3.5017, w = 3.5832, b = 1.1461
Epoch  70: Loss = 3.2460, w = 3.5591, b = 1.3037
Epoch  80: Loss = 3.0100, w = 3.5360, b = 1.4550
Epoch  90: Loss = 2.7924, w = 3.5138, b = 1.6004
Epoch 100: Loss = 2.5917, w = 3.4925, b = 1.7401

5. Kết quả cuối cùng:
w = 3.4925 (mong đợi: 3.0)
b = 1.7401 (mong đợi: 5.0)
Loss cuối cùng: 2.5917


In [36]:
# Pytorch with Tensor

In [37]:
import torch
import numpy as np 

In [38]:
torch.__version__

'2.9.0+cpu'

In [40]:
# Chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [41]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [42]:
print(x.dtype)

torch.int64


In [43]:
print(x.type())

torch.LongTensor


In [44]:
arr2 = np.arange(0., 12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [45]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [46]:
# Copy and sharing

x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [47]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5])


In [48]:
arr = np.arange(0,5)
x = torch. tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [49]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN 04

Giải thích 2 trường hợp trên

In [11]:
import torch
import numpy as np

print("TRƯỜNG HỢP 1: torch.from_numpy() - Chia sẻ bộ nhớ")

# Tạo numpy array
arr1 = np.array([1, 2, 3, 4, 5])
print(f"Numpy array ban đầu: {arr1}")

# Chuyển đổi sang tensor bằng from_numpy()
x1 = torch.from_numpy(arr1)
print(f"Tensor sau khi chuyển: {x1}")

# Thay đổi giá trị của numpy array
arr1[0] = 99
print(f"\nSau khi thay đổi arr1[0] = 99:")
print(f"Numpy array: {arr1}")
print(f"Tensor:      {x1}")

print("\n=> Tensor cũng thay đổi")
print("   torch.from_numpy() TẠO TENSOR CHIA SẺ BỘ NHỚ với numpy array")
print("   Khi array thay đổi -> tensor cũng thay đổi theo\n")


print("TRƯỜNG HỢP 2: torch.tensor() - Tạo bản sao")

# Tạo numpy array mới
arr2 = np.arange(0, 5)
print(f"Numpy array ban đầu: {arr2}")

# Chuyển đổi sang tensor bằng tensor()
x2 = torch.tensor(arr2)
print(f"Tensor sau khi chuyển: {x2}")

# Thay đổi giá trị của numpy array
arr2[0] = 99
print(f"\nSau khi thay đổi arr2[0] = 99:")
print(f"Numpy array: {arr2}")
print(f"Tensor:      {x2}")

print("\n=> Tensor KHÔNG thay đổi")
print("   torch.tensor() TẠO BẢN SAO ĐỘC LẬP trong bộ nhớ")
print("   Khi array thay đổi -> tensor vẫn giữ nguyên giá trị ban đầu\n")

print("KẾT LUẬN")
print("torch.from_numpy(): Chia sẻ bộ nhớ (memory sharing)")
print("                    + Ưu điểm: Tiết kiệm bộ nhớ, nhanh")
print("                    + Nhược điểm: Thay đổi array ảnh hưởng tensor")
print()
print("torch.tensor():     Tạo bản sao (memory copy)")
print("                    + Ưu điểm: An toàn, độc lập")
print("                    + Nhược điểm: Tốn thêm bộ nhớ")

TRƯỜNG HỢP 1: torch.from_numpy() - Chia sẻ bộ nhớ
Numpy array ban đầu: [1 2 3 4 5]
Tensor sau khi chuyển: tensor([1, 2, 3, 4, 5])

Sau khi thay đổi arr1[0] = 99:
Numpy array: [99  2  3  4  5]
Tensor:      tensor([99,  2,  3,  4,  5])

=> Tensor cũng thay đổi
   torch.from_numpy() TẠO TENSOR CHIA SẺ BỘ NHỚ với numpy array
   Khi array thay đổi -> tensor cũng thay đổi theo

TRƯỜNG HỢP 2: torch.tensor() - Tạo bản sao
Numpy array ban đầu: [0 1 2 3 4]
Tensor sau khi chuyển: tensor([0, 1, 2, 3, 4])

Sau khi thay đổi arr2[0] = 99:
Numpy array: [99  1  2  3  4]
Tensor:      tensor([0, 1, 2, 3, 4])

=> Tensor KHÔNG thay đổi
   torch.tensor() TẠO BẢN SAO ĐỘC LẬP trong bộ nhớ
   Khi array thay đổi -> tensor vẫn giữ nguyên giá trị ban đầu

KẾT LUẬN
torch.from_numpy(): Chia sẻ bộ nhớ (memory sharing)
                    + Ưu điểm: Tiết kiệm bộ nhớ, nhanh
                    + Nhược điểm: Thay đổi array ảnh hưởng tensor

torch.tensor():     Tạo bản sao (memory copy)
                    + Ưu điểm: An

# BTVN 05

Tạo tensor với
 + empty
 + zeros
 + ones
 + random
 + Reshape với view và view as




In [9]:
import torch

print("1. TẠO TENSOR VỚI EMPTY")
empty_tensor = torch.empty(3, 4)
print(f"Shape: {empty_tensor.shape}")
print(empty_tensor)
print()

print("2. TẠO TENSOR VỚI ZEROS")
zeros_tensor = torch.zeros(2, 3, 4)
print(f"Shape: {zeros_tensor.shape}")
print(zeros_tensor)
print()

print("3. TẠO TENSOR VỚI ONES")
ones_tensor = torch.ones(4, 3)
print(f"Shape: {ones_tensor.shape}")
print(ones_tensor)
print()

print("4. TẠO TENSOR VỚI RANDOM")
random_tensor = torch.rand(3, 3)
print(f"Shape: {random_tensor.shape}")
print(random_tensor)
print()

print("5. RESHAPE VỚI VIEW")
original = torch.arange(12)
print(f"Tensor gốc: {original}")
print(f"Shape: {original.shape}")

reshaped = original.view(3, 4)
print(f"\nSau khi view(3, 4):")
print(reshaped)
print(f"Shape: {reshaped.shape}")
print()

print("6. RESHAPE VỚI VIEW_AS")
original2 = torch.arange(24)
print(f"Tensor gốc: shape {original2.shape}")
print(original2)

target_shape = torch.zeros(4, 6)
print(f"\nTarget shape: {target_shape.shape}")

reshaped_as = original2.view_as(target_shape)
print(f"\nSau khi view_as(target_shape):")
print(reshaped_as)
print(f"Shape: {reshaped_as.shape}")


1. TẠO TENSOR VỚI EMPTY
Shape: torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

2. TẠO TENSOR VỚI ZEROS
Shape: torch.Size([2, 3, 4])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

3. TẠO TENSOR VỚI ONES
Shape: torch.Size([4, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

4. TẠO TENSOR VỚI RANDOM
Shape: torch.Size([3, 3])
tensor([[0.2859, 0.5736, 0.4983],
        [0.7362, 0.8096, 0.0706],
        [0.0909, 0.0997, 0.4986]])

5. RESHAPE VỚI VIEW
Tensor gốc: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Sau khi view(3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])

6. RESHAPE VỚI VIEW_AS
Tensor gốc: shape torch.Size([24])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12