# DEEP LEARNING
# Tuần 2: Numpy, Pandas, Matplotlib

# 1. NUMPY

In [3]:
# Numpy là thư viện kiểu list
# vì:
# + numpy nhanh
# + có nhiều hàm tích hợp dễ sử dụng cho AI

# Để sử dụng numpy thì: pip install numpy
import numpy as np

In [4]:
# Thử tạo 1 list
python_list = [1, 2, 3]

# Chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [1]:
# List trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [5]:
my_list = [1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [6]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [7]:
# Chuyển đổi kiểu dữ liệu
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [8]:
# accessing và indexing 

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])  # hoặc x = np.array(range(1, 9))

In [ ]:
# Lấy số 4

x[3] 

np.int64(4)

In [ ]:
# Lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
# Lấy 1, 2, 3

x[0:3]

array([1, 2, 3])

In [ ]:
# Lấy từ 3-8 theo 3 cách

print(x[2:8])
print(x[2:])
print(x[2:-1]) #C3 không đúng

[3 4 5 6 7 8]
[3 4 5 6 7 8]
[3 4 5 6 7]


In [21]:
# Lấy số 3 và số 5

x[2], x[4]

(np.int64(3), np.int64(5))

In [22]:
# Đặt danh sách các index muốn truy cập

x [[2,4]]

array([3, 5])

In [36]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Lấy số 2

np_list[0, 1]


np.int64(2)

In [ ]:
# Lấy số 6

np_list[2, 1]

np.int64(6)

In [43]:
# Lấy [3, 4], [5, 6]

np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [44]:
np_list[1:]

array([[3, 4],
       [5, 6]])

In [45]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [50]:
# Lấy 1, 3, 5
np_list[[0,1,2], 0]

array([1, 3, 5])

In [ ]:
np_list[:, 0]

array([1, 3, 5])

In [53]:
# Lấy 1 và 5 theo 2 cách
np_list[[0, 2], 0]

array([1, 5])

In [58]:
np_list[0::2,0]

array([1, 5])

In [59]:
x = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]

np_list = np.array(x)

np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [72]:
# Lấy 2, 6, 10, 14

np_list[:, 1]

array([ 2,  6, 10, 14])

In [70]:
np_list[0::,1]

array([ 2,  6, 10, 14])

In [73]:
# Lấy 7 và 11

np_list[1:3, 2]

array([ 7, 11])

In [74]:
np_list[[1,2], 2]

array([ 7, 11])

In [ ]:
# Lấy 4, 7, 10

np_list([0, 1, 2],[3, 2, 1])

array([ 4,  8, 12, 16])

In [76]:
# Lấy 16, 15, 14, 13
np_list[3, ::-1]

array([16, 15, 14, 13])

In [77]:
np_list[-1, ::-1]

array([16, 15, 14, 13])

In [78]:
np_list[3, [3, 2, 1, 0]]

array([16, 15, 14, 13])

In [1]:
# BTVN 01
# Cho ma trận = [[99, 99, 99],
#                [99, 99, 99],
#                [99, 99, 99]]

# Hãy tưởng tượng ô 99 trống
# Giả sử 1 là X
# Giả sử 0 là O

# Lấy đầu vào từ phía X và phía O luân phiên
# Nếu đầu vào từ phía X là (0,0)

# Ma trận sẽ trở thành
# [[99, 99, 99],
#  [99, 99, 99],
#  [99, 99, 99]]

# Nếu đầu vào từ phía O cũng là (0,0)
# Thông báo họ nhập lại
# Nếu không thì điền vào ma trận

# Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.




import numpy as np

# Khởi tạo ma trận 3x3
matrix = np.array([[99, 99, 99],
                   [99, 99, 99],
                   [99, 99, 99]])

def check_win(mat):
    """Kiểm tra xem có ai thắng chưa"""
    # Kiểm tra hàng ngang
    for i in range(3):
        if mat[i, 0] == mat[i, 1] == mat[i, 2] != 99:
            return mat[i, 0]
    
    # Kiểm tra hàng dọc
    for j in range(3):
        if mat[0, j] == mat[1, j] == mat[2, j] != 99:
            return mat[0, j]
    
    # Kiểm tra đường chéo chính
    if mat[0, 0] == mat[1, 1] == mat[2, 2] != 99:
        return mat[0, 0]
    
    # Kiểm tra đường chéo phụ
    if mat[0, 2] == mat[1, 1] == mat[2, 0] != 99:
        return mat[0, 2]
    
    return None

def display_board(mat):
    """Hiển thị bàn cờ"""
    display = mat.copy().astype(str)
    display[mat == 1] = 'X'
    display[mat == 0] = 'O'
    display[mat == 99] = '-'
    print("\nBàn cờ hiện tại:")
    for row in display:
        print(' '.join(row))

# Chơi game
current_player = 1  # 1 là X, 0 là O
move_count = 0

print("Hướng dẫn: Nhập tọa độ dưới dạng 'hàng,cột' (ví dụ: 0,0)")
print("X đi trước!")

while move_count < 9:
    display_board(matrix)
    
    player_name = 'X' if current_player == 1 else 'O'
    print(f"\nLượt của {player_name}")
    
    # Nhập tọa độ
    try:
        pos = input(f"Nhập vị trí cho {player_name} (hàng,cột): ")
        row, col = map(int, pos.split(','))
        
        # Kiểm tra tọa độ hợp lệ
        if row < 0 or row > 2 or col < 0 or col > 2:
            print("Tọa độ không hợp lệ! Vui lòng nhập lại (0-2)")
            continue
        
        # Kiểm tra ô đã được đánh chưa
        if matrix[row, col] != 99:
            print("Ô này đã được đánh rồi! Vui lòng chọn ô khác")
            continue
        
        # Đánh dấu
        matrix[row, col] = current_player
        move_count += 1
        
        # Kiểm tra thắng
        winner = check_win(matrix)
        if winner is not None:
            display_board(matrix)
            winner_name = 'X' if winner == 1 else 'O'
            print(f"\n{winner_name} THẮNG!")
            break
        
        # Kiểm tra hòa
        if move_count == 9:
            display_board(matrix)
            print("\nHÒA!")
            break
        
        # Chuyển lượt
        current_player = 1 - current_player
        
    except ValueError:
        print("Định dạng không đúng! Vui lòng nhập theo dạng 'hàng,cột'")
    except KeyboardInterrupt:
        print("\nTrò chơi kết thúc!")
        break

Hướng dẫn: Nhập tọa độ dưới dạng 'hàng,cột' (ví dụ: 0,0)
X đi trước!

Bàn cờ hiện tại:
- - -
- - -
- - -

Lượt của X

Bàn cờ hiện tại:
- X -
- - -
- - -

Lượt của O

Bàn cờ hiện tại:
- X -
- - O
- - -

Lượt của X

Bàn cờ hiện tại:
- X X
- - O
- - -

Lượt của O
Tọa độ không hợp lệ! Vui lòng nhập lại (0-2)

Bàn cờ hiện tại:
- X X
- - O
- - -

Lượt của O
Ô này đã được đánh rồi! Vui lòng chọn ô khác

Bàn cờ hiện tại:
- X X
- - O
- - -

Lượt của O
Ô này đã được đánh rồi! Vui lòng chọn ô khác

Bàn cờ hiện tại:
- X X
- - O
- - -

Lượt của O
Tọa độ không hợp lệ! Vui lòng nhập lại (0-2)

Bàn cờ hiện tại:
- X X
- - O
- - -

Lượt của O
Tọa độ không hợp lệ! Vui lòng nhập lại (0-2)

Bàn cờ hiện tại:
- X X
- - O
- - -

Lượt của O

Bàn cờ hiện tại:
- X X
- - O
- - O

Lượt của X

Bàn cờ hiện tại:
- X X
- - O
- X O

Lượt của O

Bàn cờ hiện tại:
- X X
- O O
- X O

Lượt của X

Bàn cờ hiện tại:
- X X
X O O
- X O

Lượt của O

Bàn cờ hiện tại:
O X X
X O O
- X O

O THẮNG!


In [2]:
# BTVN 02

#y = [[1, 2, 3],
 #    [4, 5, 6],
 #    [7, 8, 9]]

# Lấy 4, 5, 6
# Lấy 2, 5
# Lấy 3, 4
# Lấy 9, 6, 3


import numpy as np

y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Ma trận y:")
print(y)

# Lấy 4, 5, 6
print("\n1. Lấy 4, 5, 6:")
print("Cách 1:", y[1, :])
print("Cách 2:", y[1])

# Lấy 2, 5
print("\n2. Lấy 2, 5:")
print("Cách 1:", y[[0, 1], 1])
print("Cách 2:", y[0:2, 1])
print("Cách 3:", y[:2, 1])

# Lấy 3, 4
print("\n3. Lấy 3, 4:")
print("Cách 1:", y[[0, 1], [2, 0]])
print("Cách 2:", np.array([y[0, 2], y[1, 0]]))

# Lấy 9, 6, 3
print("\n4. Lấy 9, 6, 3:")
print("Cách 1:", y[::-1, 2])
print("Cách 2:", y[[2, 1, 0], 2])
print("Cách 3:", y[:, 2][::-1])

Ma trận y:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. Lấy 4, 5, 6:
Cách 1: [4 5 6]
Cách 2: [4 5 6]

2. Lấy 2, 5:
Cách 1: [2 5]
Cách 2: [2 5]
Cách 3: [2 5]

3. Lấy 3, 4:
Cách 1: [3 4]
Cách 2: [3 4]

4. Lấy 9, 6, 3:
Cách 1: [9 6 3]
Cách 2: [9 6 3]
Cách 3: [9 6 3]


In [3]:
# BTVN 03

# Cho x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# 1. Xuất ra các giá trị chẵn sử dụng if
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension




import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Mảng x:", x)

#1. Sử dụng if
print("\n1. Xuất các giá trị chẵn sử dụng if:")
even_numbers_if = []
for num in x:
    if num % 2 == 0:
        even_numbers_if.append(num)
print("Kết quả:", even_numbers_if)

#2. Sử dụng list comprehension
print("\n2. Xuất các giá trị chẵn sử dụng list comprehension:")
even_numbers_comp = [num for num in x if num % 2 == 0]
print("Kết quả:", even_numbers_comp)

Mảng x: [ 1  2  3  4  5  6  7  8  9 10]

1. Xuất các giá trị chẵn sử dụng if:
Kết quả: [np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]

2. Xuất các giá trị chẵn sử dụng list comprehension:
Kết quả: [np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]


In [80]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [83]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [84]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
idx = [ True, True, True, False, True, True, True, False,  True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [88]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
cond1 = np_x % 2 != 0 
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
# BTVN 04

# Tạo 1 mảng numpy có kích thước 150 x 5. Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình.
# Tách mảng dựa trên bố cục đầu tiên thành 1 biến có tên là X và cột cuối cùng thành y

# Tách mảng X thành X_train và X_test trong đó X_train chứa 70% dữ liệu & tách y thành y_train và y_test trong đó y_train chứa 70% dữ liệu.
# Tạo 10 tập dữ liệu X_train không chồng chéo nhau




import numpy as np

# Tạo mảng numpy 150x5 với dữ liệu ngẫu nhiên
np.random.seed(42)  # Để kết quả có thể lặp lại

# Giả lập dữ liệu sinh viên
# Cột: [Chiều cao (cm), Cân nặng (kg), Tuổi, Lương (triệu), Điểm TB]
data = np.random.rand(150, 5)
data[:, 0] = data[:, 0] * 30 + 150  # Chiều cao: 150-180cm
data[:, 1] = data[:, 1] * 40 + 45   # Cân nặng: 45-85kg
data[:, 2] = data[:, 2] * 5 + 18    # Tuổi: 18-23
data[:, 3] = data[:, 3] * 15 + 5    # Lương: 5-20 triệu
data[:, 4] = data[:, 4] * 4 + 6     # Điểm: 6-10

print("Shape của dữ liệu:", data.shape)
print("\n5 mẫu đầu tiên:")
print(data[:5])

# Tách X và y
X = data[:, :-1]  # 4 cột đầu (bỏ cột cuối)
y = data[:, -1]   # Cột cuối

print(f"\nShape của X: {X.shape}")
print(f"Shape của y: {y.shape}")

# Tách train/test (70% train, 30% test)
train_size = int(0.7 * len(data))

X_train = X[:train_size]
X_test = X[train_size:]
y_train = y[:train_size]
y_test = y[train_size:]

print(f"\nX_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Tạo 10 tập dữ liệu X_train không chồng chéo (K-Fold với k=10)
print("Tạo 10 fold không chồng chéo từ X_train:")

n_folds = 10
fold_size = len(X_train) // n_folds

folds_X = []
folds_y = []

for i in range(n_folds):
    start_idx = i * fold_size
    if i == n_folds - 1:  # Fold cuối lấy hết phần còn lại
        end_idx = len(X_train)
    else:
        end_idx = (i + 1) * fold_size
    
    fold_X = X_train[start_idx:end_idx]
    fold_y = y_train[start_idx:end_idx]
    
    folds_X.append(fold_X)
    folds_y.append(fold_y)
    
    print(f"Fold {i+1}: X shape = {fold_X.shape}, y shape = {fold_y.shape}")

# Kiểm tra không chồng chéo
print("\nTổng số mẫu trong các fold:", sum([len(f) for f in folds_X]))
print("Số mẫu trong X_train:", len(X_train))
print("Các fold không chồng chéo")

Shape của dữ liệu: (150, 5)

5 mẫu đầu tiên:
[[161.23620357  83.02857226  21.65996971  13.97987726   6.62407456]
 [154.67983561  47.32334449  22.33088073  14.01672518   8.83229031]
 [150.61753483  83.79639409  22.1622132    8.18508666   6.72729987]
 [155.5021353   57.16968972  20.62378216  11.47917528   7.16491656]
 [168.35558684  50.57975443  19.46072324  10.49542765   7.82427994]]

Shape của X: (150, 4)
Shape của y: (150,)

X_train shape: (105, 4)
X_test shape: (45, 4)
y_train shape: (105,)
y_test shape: (45,)
Tạo 10 fold không chồng chéo từ X_train:
Fold 1: X shape = (10, 4), y shape = (10,)
Fold 2: X shape = (10, 4), y shape = (10,)
Fold 3: X shape = (10, 4), y shape = (10,)
Fold 4: X shape = (10, 4), y shape = (10,)
Fold 5: X shape = (10, 4), y shape = (10,)
Fold 6: X shape = (10, 4), y shape = (10,)
Fold 7: X shape = (10, 4), y shape = (10,)
Fold 8: X shape = (10, 4), y shape = (10,)
Fold 9: X shape = (10, 4), y shape = (10,)
Fold 10: X shape = (15, 4), y shape = (15,)

Tổng số m